language: rust
sudo: required
os:
- linux
- osx
rust:
- nightly-2019-04-25
services:
- docker
before_deploy: "./build-release falconeri ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "falconeri-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
    skip_cleanup: true
    on:
      rust: stable
      tags: true
  - provider: pages
    skip-cleanup: true
    local-dir: gh-pages
    keep-history: true
    github-token: $GITHUB_TOKEN
    on:
      rust: stable
      condition: $TRAVIS_OS_NAME = linux
