FROM clux/muslrust:stable

# Copy source code
COPY --chown=rust:rust . .

# Extra arguments to pass to cargo.
ENV CARGO_ARGS=

# Build all binaries.
CMD if [ -d target ]; then chown -R rust:rust /volume/.cargo/git /volume/.cargo/registry /volume/target; fi && \
    cargo build --all ${CARGO_ARGS} --target x86_64-unknown-linux-musl && \
    cd guide && mdbook build
