[package]
name = "falconeri_common"
version = "1.0.0-beta.13"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
base64 = "0.22.1"
cast = { version = "0.3.0", features = ["std"] }
chrono = { version = "0.4.42", features = ["serde"] }
diesel = { version = "2.3.4", features = ["chrono", "postgres", "r2d2", "serde_json", "uuid"] }
diesel_migrations = "2.3.1"
pq-sys = "0.7"
handlebars = "6.3.2"
humantime-serde = "1.1.1"
lazy_static = "1.5.0"
r2d2 = "0.8.10"
rand = "0.9.2"
regex = "1.12.2"
reqwest = { version = "0.13.1", default-features = false, features = ["blocking", "json", "rustls"] }
semver = "1.0.27"
serde = "1.0.228"
serde_json = "1.0"
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5.7"
uuid = { version = "1.19.0", features = ["serde", "v4"] }
google-cloud-storage = { git = "https://github.com/googleapis/google-cloud-rust.git", package = "google-cloud-storage" }
google-cloud-auth = { git = "https://github.com/googleapis/google-cloud-rust.git", package = "google-cloud-auth" }
tokio = { version = "1.48", features = ["rt-multi-thread", "macros", "fs"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = "0.3"
bytes = "1.11"
glob = "0.3"
