[package]
name = "falconeri_common"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
chrono = "0.4.4"
diesel = { version = "1.3.0", features = ["chrono", "postgres", "serde_json", "uuid"] }
failure = "0.1.1"
serde_json = "1.0"
uuid = "0.6.5"
