[package]
name = "falconeri_common"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
base64 = "0.9.2"
chrono = "0.4.4"
diesel = { version = "1.3.0", features = ["chrono", "postgres", "serde_json", "uuid"] }
diesel_migrations = "1.3.0"
failure = "0.1.1"
log = "0.4.3"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0"
uuid = "0.6.5"
