[package]
name = "falconeri_common"
version = "0.1.7"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
base64 = "0.9.2"
bson = "0.13.0"
cast = "0.2.2"
chrono = { version = "0.4.4", features = ["serde"] }
common_failures = "0.1.1"
diesel = { version = "1.3.0", features = ["chrono", "postgres", "serde_json", "uuid"] }
diesel_migrations = "1.3.0"
failure = "0.1.1"
lazy_static = "1.0.2"
log = "0.4.3"
magnet_derive = "0.4.0"
magnet_schema = "0.4.0"
rand = "0.5.4"
regex = "1.0.2"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
