[package]
name = "falconerid"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

[dependencies]
falconeri_common = { path = "../falconeri_common" }
headers = "0.2"
rocket = "0.4.0"
rocket_contrib = { version = "0.4.0", features = ["uuid"] }
serde = "1.0"
serde_derive = "1.0"
