[global]
port = 8089

[development]
# We only run inside a container, so bind on a public port.
address = "0.0.0.0"
workers = 4
log = "normal"

[production]
address = "0.0.0.0"
workers = 64
log = "critical"
