[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
name = "falconeri"
version = "0.1.0"

[dependencies]
base64 = "0.9.2"
env_logger = "0.5.10"
failure = "0.1.1"
falconeri_common = { path = "../falconeri_common" }
handlebars = "1.0.0-beta.4"
log = "0.4.3"
# Needed for ekidd/rust-musl-builder.
openssl = "*"
openssl-probe = "0.1.2"
prettytable-rs = "0.7.0"
rand = "0.5.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2.10"
