[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
name = "falconeri"
version = "0.1.0"

[dependencies]
falconeri_common = { path = "../falconeri_common" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
